src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom_catg = null;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Formation::class)]
    private Collection $liste_formations;

    public function __construct()
    {
        $this->liste_formations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCatg(): ?string
    {
        return $this->nom_catg;
    }

    public function setNomCatg(string $nom_catg): self
    {
        $this->nom_catg = $nom_catg;

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getListeFormations(): Collection
    {
        return $this->liste_formations;
    }

    public function addListeFormation(Formation $listeFormation): self
    {
        if (!$this->liste_formations->contains($listeFormation)) {
            $this->liste_formations->add($listeFormation);
            $listeFormation->setCategorie($this);
        }

        return $this;
    }

    public function removeListeFormation(Formation $listeFormation): self
    {
        if ($this->liste_formations->removeElement($listeFormation)) {
            // set the owning side to null (unless already changed)
            if ($listeFormation->getCategorie() === $this) {
                $listeFormation->setCategorie(null);
            }
        }

        return $this;
    }
    //  ************************ To String ************************************
    public function __toString()
    {
        return $this->nom_catg;
    }
}

src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nomForm;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dureeForm;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $descriptionForm;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="formations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToMany(targetEntity=Utilisateur::class, inversedBy="formations")
     */
    private $utilisateur;

    public function __construct()
    {
        $this->utilisateur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomForm(): ?string
    {
        return $this->nomForm;
    }

    public function setNomForm(?string $nomForm): self
    {
        $this->nomForm = $nomForm;

        return $this;
    }

    public function getDureeForm(): ?int
    {
        return $this->dureeForm;
    }

    public function setDureeForm(?int $dureeForm): self
    {
        $this->dureeForm = $dureeForm;

        return $this;
    }

    public function getDescriptionForm(): ?string
    {
        return $this->descriptionForm;
    }

    public function setDescriptionForm(?string $descriptionForm): self
    {
        $this->descriptionForm = $descriptionForm;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Utilisateur>
     */
    public function getUtilisateur(): Collection
    {
        return $this->utilisateur;
    }

    public function addUtilisateur(Utilisateur $utilisateur): self
    {
        if (!$this->utilisateur->contains($utilisateur)) {
            $this->utilisateur[] = $utilisateur;
        }

        return $this;
    }

    public function removeUtilisateur(Utilisateur $utilisateur): self
    {
        $this->utilisateur->removeElement($utilisateur);

        return $this;
    }
}

templates/formation/ListFormation.html.twig
{% extends 'FrontOfficeVisiteur.html.twig' %}

{% block body %}
	<section
		class="dashboard section">
		<!-- Container Start -->
		<div
			class="container">
			<!-- Row Start -->
			<div class="row">
				<div
					class="col-lg-12">
					<!-- Recently Favorited -->
					<div class="widget dashboard-container my-adslist">
						<h3 class="widget-header">Liste des Formations</h3>
						<table class="table table-responsive product-dashboard-table">
							<thead>
								<tr>
									<th>Nom Formation</th>
									<th>Description</th>
									<th class="text-center">Catégorie</th>
									<th class="text-center">Action</th>
								</tr>
							</thead>
							<tbody>
								{% for key, frm in formations %}
									<tr>
										<td class="product-titlr">
											{{ frm.nomForm }}</td>
										<td class="product-details">
											{{ frm.descriptionForm }}
										</td>
										<td class="product-category">
											<span class="categories">{{ frm.categorie.nomCatg }}</span>
										</td>
										<td class="action" data-title="Action">
											<div class="">
												<ul class="list-inline justify-content-center">
													<li class="list-inline-item">
														<a data-toggle="tooltip" data-placement="top" title="Détails" class="view" href="{{ path('show_formation', {id: frm.id}) }}">
															<i class="fa fa-eye"></i>
														</a>
													</li>
												</ul>
											</div>
										</td>
									</tr>
								{% else %}
									pas de formation trouvée
								{% endfor %}
							</tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>{% endblock %}

templates/formation/det_formation.html.twig
{% extends 'FrontOfficeVisiteur.html.twig' %}


{% block body %}
	<h1>Formation :
		{{ formation.id }}</h1>
	<article>
		<h3>Titre :
			{{ formation.nomForm | raw }}</h3>
		<div class="row">

			<div class="col-lg-12">
				<p>
					<b>Catégorie :
					</b>
					{{ formation.categorie.nomCatg | raw }}
					<br><b>Description :
					</b>
					{{ formation.descriptionForm | raw }}
					<br><b>Durée :
					</b>
					{{ formation.dureeForm }}
					jours.</p>
			</div>

			<div class="col-lg-12">
				<div class="form-group">
					<a href="{{ path('get_FormationList') }}" class="btn btn-info float-start">Retour</a>
				</div>
			</div>
		</div>
	</article>
{% endblock %}