src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\JoinColumn;
#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank (message: "Le titre est requis!")]
    private ?string $titre_rec = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank (message: "Le type est requis!")]
    private ?string $type_rec = null;
   
    #[assert\Range(min: 'now',)]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank (message: "La date est requise!")]
    private ?\DateTimeInterface $date_rec = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank (message: "La description est requise!")]
    #[Assert\Length (max:255)]
    private ?string $contenu_rec = null;

    #[ORM\Column]
    #[Assert\NotBlank (message: "Le status est requise!")]
    #[Assert\Length (max:255)]
    #[Assert\Choice(choices: ["NON_TRAITE", "TRAITE", "EN_ATTENTE"])]
    private ?string $statut_rec = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank (message: "User Name est requise!")]
    private ?string $username = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreRec(): ?string
    {
        return $this->titre_rec;
    }

    public function setTitreRec(string $titre_rec): self
    {
        $this->titre_rec = $titre_rec;

        return $this;
    }

    public function getTypeRec(): ?string
    {
        return $this->type_rec;
    }

    public function setTypeRec(string $type_rec): self
    {
        $this->type_rec = $type_rec;

        return $this;
    }

    public function getDateRec(): ?\DateTimeInterface
    {
        return $this->date_rec;
    }

    public function setDateRec(\DateTimeInterface $date_rec): self
    {
        $this->date_rec = $date_rec;

        return $this;
    }

    public function getContenuRec(): ?string
    {
        return $this->contenu_rec;
    }

    public function setContenuRec(string $contenu_rec): self
    {
        $this->contenu_rec = $contenu_rec;

        return $this;
    }

    public function getStatutRec(): ?string
    {
        return $this->statut_rec;
    }

    public function setStatutRec(string $statut_rec): self
    {
        $this->statut_rec = $statut_rec;

        return $this;
    }
    public function __toString()
    {
        return $this->getUsername();
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre_rec')
            ->add('type_rec')
            ->add('date_rec')
            ->add('contenu_rec')
            ->add('statut_rec')
            ->add('username')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
    //sms
    public  function sms(){
        // Your Account SID and Auth Token from twilio.com/console
                $sid = 'AC9cbf3d245cc90ddb31db6e6edd046fd1';
                $auth_token = '386f12af78bc83af84023dde83fbe8f2';
        // In production, these should be environment variables. E.g.:
        // $auth_token = $_ENV["TWILIO_AUTH_TOKEN"]
        // A Twilio number you own with SMS capabilities
                $twilio_number = "+16073576523";
        
                $client = new Client($sid, $auth_token);
                $client->messages->create(
                // the number you'd like to send the message to
                    '+21696869820',
                    [
                        // A Twilio phone number you purchased at twilio.com/console
                        'from' => '+21696869820',
                        // the body of the text message you'd like to send
                        'body' => 'votre reclamation a été traité merci de nous contacter pour plus de détail!'
                    ]
                );
            }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\SearchType;
use Knp\Snappy\Pdf;
use Dompdf\Dompdf;

#[Route('/reclamation')]
class ReclamationController extends AbstractController
{

    #[Route('/pdf/{id}', name: 'export_reclamation_pdf', methods: ['GET'])]
    public function exportAction(Pdf $pdf, $id)
    {
        $reclamation = $this->getDoctrine()->getRepository(Reclamation::class)->find($id);
        $html = $this->renderView('reclamation/pdf.html.twig', [
            'reclamation' => $reclamation,
        ]);
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->render();

        return new Response(
            $dompdf->stream('resume', ["Attachment" => false]),
            Response::HTTP_OK,
            ['Content-Type' => 'application/pdf']
        );
    }

    #[Route('/', name: 'app_front_reclamation_index', methods: ['GET'])]
    public function indexFront(ReclamationRepository $reclamationRepository): Response
    {
        return $this->render('reclamation/index_front.html.twig', [
            'reclamation' => $reclamationRepository->findAll(),
        ]);
    }

    #[Route('/rec', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(ReclamationRepository $reclamationRepository): Response
    {
        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reclamation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReclamationRepository $reclamationRepository): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);
            $reclamationRepository->sms();
            return $this->redirectToRoute('page_utilisateur_connecte', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_show', methods: ['GET'])]
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }
    #[Route('/his', name: 'app_reclamation_show1', methods: ['GET'])]
    public function show1(Reclamation $reclamation): Response
    {

        return $this->render('reclamation/historique.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_delete', methods: ['POST'])]
    public function delete(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reclamation->getId(), $request->request->get('_token'))) {
            $reclamationRepository->remove($reclamation, true);
        }

        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('search', name: 'reclamation_search')]

    public function search(ReclamationRepository $reclamationRepository, Request $request): Response
    {
        $issetTitre = isset($_GET['titre']);
        if ($issetTitre) {

            $reclamations = $reclamationRepository->searchReclamations($_GET['titre']);

            return $this->render('reclamation/index.html.twig', [
                'reclamations' => $reclamations,
            ]);
        }

        return $this->render('reclamation/search.html.twig', [
            'reclamationsearch' => $form->createView(),
        ]);
    }
}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reclamation/edit.html.twig
{% extends 'FrontOfficeConnecte.html.twig' %}

{% block title %}
	Modifier la reclamation
{% endblock %}

{% block body %}
	<div id="layoutSidenav_content">
		<main>
			<div id="layoutAuthentication">
				<div id="layoutAuthentication_content">
					<main>
						<div class="container">
							<div class="row justify-content-center">
								<div class="col-lg-7">
									<div class="card shadow-lg border-0 rounded-lg mt-5">
										<div class="card-header">
											<h3 class="text-center font-weight-light my-4">Modifier la reclamation</h3>
										</div>
										<div class="card-body">
											{{form_start(form,{'attr':{'novalidate':'novalidate'}})}}
											<div class="row mb-3">
												
												<div class="col-md-6">
													<div class="form-floating mb-3" >
											        	{{form_widget(form.titre_rec,{'attr':{'class':'form-control'}})}}
												        <label for="inputEmail">Titre</label>
											        </div>
                                                    <div class="form-floating mb-3 mb-md-0">
														{{form_widget(form.type_rec,{'attr':{'class':'form-control'}})}}
														<label for="inputFirstName">Type</label>
													</div>
                                                    <div class="form-floating">
														{{form_widget(form.date_rec,{'attr':{'class':'form-control datetimepicker'}})}}
														<label for="inputLastName">Date et Heure</label>
													</div>
												</div>
											</div>
											
											<div class="row mb-3">
												<div class="col-md-6">
													<div class="form-floating mb-3 mb-md-0">
														{{form_widget(form.contenu_rec,{'attr':{'class':'form-control'}})}}
														<label for="inputFirstName">contenu</label>
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-floating">
														{{form_widget(form.statut_rec,{'attr':{'class':'form-control'}})}}
														<label for="inputLastName">statut_rec</label>
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-floating">
														{{form_widget(form.username,{'attr':{'class':'form-control'}})}}
														<label for="inputLastName">username</label>
													</div>
												</div>
											</div>

											<div class="row mb-3">
												<div class="col-md-6">
													
												</div>
											</div>
											<div class="mt-4 mb-0">
												<div class="d-grid">
													
													{{ include('reclamation/_form.html.twig', {'button_label': 'Modifier'}) }}
												</div>
											</div>
											<div class="mt-4 mb-0">
												<div class="d-grid" >
													{{ include('reclamation/_delete_form.html.twig') }}
												</div>
											</div>


											{{form_end(form)}}
										</div>
										<div class="card-footer text-center py-3">
											<div class="small">
												<a type="button" class="btn btn-primary" href="{{ path('app_reclamation_index') }}">Retour à la liste</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</main>
				</div>
			</main>
		{% endblock %}

templates/reclamation/historique.html.twig
{% extends 'BACK/base.html.twig' %}
{% block body %}

<div  id="layoutSidenav_content">
    <table class="table"style="color: BLACK;" >
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Type</th>
                <th>Date</th>
                <th>Contenu</th>
                <th>Statut</th>
                <th>User Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
		{% if reclamation.username = }
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.titreRec }}</td>
                <td>{{ reclamation.typeRec }}</td>
                <td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</td>
                <td>{{ reclamation.contenuRec }}</td>
                <td>{{ reclamation.statutRec }}</td>
                <td>{{ reclamation.username }}</td>
                <td>
                    <a type="button" class="btn btn-warning" href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
                    {# <a type="button" class="btn btn-info" href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a> #}
                     <a type="button" class="btn btn-danger" href="{{ path('app_repons_new') }}">Repondre</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/reclamation/index.html.twig
{% extends 'BackOffice.html.twig' %}
{% block contenu %}


	<div id="layoutSidenav_content">
		<table class="table" style="color: BLACK;">
			<thead>
				<tr>
					<th>Id</th>
					<th>Titre</th>
					<th>Type</th>
					<th>Date</th>
					<th>Contenu</th>
					<th>Statut</th>
					<th>User Name</th>
					<th>actions</th>
				</tr>
			</thead>
			<tbody>
				{% for reclamation in reclamations %}
					<tr>
						<td>{{ reclamation.id }}</td>
						<td>{{ reclamation.titreRec }}</td>
						<td>{{ reclamation.typeRec }}</td>
						<td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</td>
						<td>{{ reclamation.contenuRec }}</td>
						<td>
							{% if reclamation.statutRec == "NON_TRAITE" %}
								<div class="progress">
									<div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
							</div>

						{%  elseif reclamation.statutRec == "EN_ATTENTE" %}
							<div class="progress">
								<div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
							</div>
						</div>

					{% elseif reclamation.statutRec == "TRAITE" %}
						<div class="progress">
							<div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
				{% endif %}
			</tbody>
		</td>
		{# <td>{{ reclamation.statutRec }}</td> #}
		<td>{{ reclamation.username }}</td>
		<td>
			<a type="button" class="btn btn-warning" href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
			<a type="button" class="btn btn-info" href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>
			<a type="button" class="btn btn-danger" href="{{ path('app_repons_new') }}">Repondre</a>
			<a class="btn btn-success" href="{{ path('export_reclamation_pdf', {'id': reclamation.id}) }}">Exporter en PDF</a>

		</td>
	</tr>
{% else %}
	<tr>
		<td colspan="7">no records found</td>
	</tr>
{% endfor %}</tbody></table>{{ include('reclamation/search.html.twig')}}</div>{% endblock %}{% block js %}<script src="{{ asset('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js') }}" crossorigin="anonymous"></script><script src="{{ asset('js_back/scripts.js') }}"></script><script src="{{ asset('https://cdn.jsdelivr.net/npm/simple-datatables@latest') }}" crossorigin="anonymous"></script><script src="{{ asset('js_back/datatables-simple-demo.js') }}"></script>{% endblock %}

templates/reclamation/index_front.html.twig
{% extends 'FrontOfficeConnecte.html.twig' %}


{% block title %}
	Reclamation
{% endblock %}

{% block body %}
	 <!-- inner-hero start -->
    <section class="inner-hero bg_img" data-background="FRONT/assets/images/bg/inner-hero.jpg">

      {# <div class="el-1 position-absolute"><img src="FRONT\assets\images\elements\inner-hero\el-1.png" alt="image"></div>
      <div class="el-2 position-absolute"><img src="FRONT\assets\images\elements\inner-hero\el-2.png" alt="image"></div>
      <div class="el-3 position-absolute"><img src="FRONT\assets\images\elements\inner-hero\el-3.png" alt="image"></div>
      <div class="el-4 position-absolute"><img src="FRONT\assets\images\elements\inner-hero\el-4.png" alt="image"></div>
      <div class="el-5 position-absolute"><img src="FRONT\assets\images\elements\inner-hero\el-5.png" alt="image"></div>
      <div class="el-6 position-absolute"><img src="FRONT\assets\images\elements\inner-hero\el-6.png" alt="image"></div> #}

      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h2 class="page-title">Reclamation</h2>
            <ul class="page-list">
              <li><a href="index.html">Acceuil</a></li>
              <li>Reclamation</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <!-- inner-hero end -->
	<!-- blog section start -->
    <section class="pt-120 pb-120">
      <div class="container">
        <div class="row mb-none-40">
          <div class="col-lg-12">
          <div class="card-footer text-center py-3">
											<div class="small">
                      <a type="button" class="btn btn-primary" href="{{ path('app_reclamation_new') }}">Create new</a>
												<a type="button" class="btn btn-primary" href="{{ path('app_reclamation_show1') }}">Voir historique</a>
											</div>
										</div>
     			
            <div class="row mt-4">
              <div class="col-lg-12">
                <nav>
                  <ul class="pagination justify-content-center align-items-center">
                    <li class="page-item disabled">
                      <a class="page-link prev" href="#" tabindex="-1" aria-disabled="true"><i class="las la-angle-double-left"></i>Prev</a>
                    </li>
                    
                    <li class="page-item active" aria-current="page">
                      <a class="page-link" href="#">1 <span class="sr-only">(current)</span></a>
                    </li>
                    
                    <li class="page-item">
                      <a class="page-link next" href="#">Next <i class="las la-angle-double-right"></i></a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- blog section end -->

	{% endblock %}

templates/reclamation/new.html.twig
{% extends 'FrontOfficeConnecte.html.twig' %}

{% block title %}
	Reclamations
{% endblock %}

{% block body %}
	<div id="layoutSidenav_content">
		<main>
			<div id="layoutAuthentication">
				{# <div id="layoutAuthentication_content"> #}
					<main>
						<div class="container">
							<div class="row justify-content-center">
								<div class="col-lg-7">
									<div class="card shadow-lg border-0 rounded-lg mt-5">
										<div class="card-header">
											<h3 class="text-center font-weight-light my-4">Créer Reclamtion</h3>
										</div>
										<div class="card-body">
											{{form_start(form,{'attr':{'novalidate':'novalidate'}})}}
											
											<div class="form-group">
												<div class="form-group">
													<div class="form-group" class="form-floating mb-3 mb-md-0" > 
													<a >Titre</a>
													{{form_widget(form.titre_rec,{'attr':{'class':'form-control'}})}}
													{% if form_errors(form.titre_rec) %}
													
														{{form_errors(form.titre_rec,{'attr':{'class':'form-control',}})}}
														
													</div>
													{% endif %}
												</div>
                                                <div class="form-floating mb-3">
													<a for="inputEmail">Type</a>
													{{form_widget(form.type_rec,{'attr':{'class':'form-control'}})}}
													{% if form_errors(form.type_rec) %}
												
												{{form_errors(form.type_rec,{'attr':{'class':'form-control'}})}}
												
											</div>
											{% endif %}
												<div class="form-group">
													<div class="form-floating">
														<a>Date et Heure</a>
														{{form_widget(form.date_rec,{'attr':{'class':'form-control'}})}}
													{% if form_errors(form.date_rec) %}
														{{form_errors(form.date_rec,{'attr':{'class':'form-control datetimepicker'}})}}
														
													</div>
													{% endif %}
												</div>
											</div>
											<br><br><br><br>
											<div class="form-group">
												<div class="col-md-6">
													<div class="form-floating mb-3 mb-md-0">
															<a for="inputFirstName">Contenu</a>
															{{form_widget(form.contenu_rec,{'attr':{'class':'form-control'}})}}
													{% if form_errors(form.contenu_rec) %}
														{{form_errors(form.contenu_rec,{'attr':{'class':'form-control'}})}}
														
													</div>
													{% endif %}
												</div>
												<div class="form-group">
													<div class="form-floating">
													<a for="inputLastName">Statut</a>
													<a for="inputLastName">1 : NON_TRAITE</a>
													<a for="inputLastName">2 : TRAITE</a>
													<a for="inputLastName">3 : EN_ATTENTE</a>
														{{form_widget(form.statut_rec,{'attr':{'class':'form-control'}})}}
													{% if form_errors(form.statut_rec) %}
													
														{{form_errors(form.statut_rec,{'attr':{'class':'form-control'}})}}
														
													</div>
													{% endif %}
												</div>
													<div class="form-group">
													<div class="form-floating">
													<a for="inputLastName">User Name</a>
														{{form_widget(form.username,{'attr':{'class':'form-control'}})}}
													{% if form_errors(form.username) %}
													
														{{form_errors(form.username,{'attr':{'class':'form-control'}})}}
														
													</div>
													{% endif %}
												</div>
											</div>
                                            <div class="mt-4 mb-0">
												<div class="d-grid" type="button" class="btn btn-primary">
													{{ include('reclamation/_form.html.twig', {'button_label': 'Valider'}, {'href':"{{ path('app_reclamation_index') }}" },{'class':'btn btn-success '}) }}
												
												</div>
											</div>
										
									</div>
								</div>
							</div>
						</div>
					</main>
				{# </div> #}
			</main>
		{% endblock %}

templates/reclamation/pdf.html.twig
<h1>Réclamation {{ reclamation.id }}</h1>
<p><b> TITRE : </b>{{ reclamation.titreRec }}</p>
<p><b> TYPE : </b>{{ reclamation.typeRec }}</p>
<p><b> DATE : </b>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</p>
<p><b> CONTENU : </b>{{ reclamation.contenuRec }}</p>
<p><b> STATUT : </b>{{ reclamation.statutRec }}</p>
<p><b> USER : </b>{{ reclamation.username }}</p>

templates/reclamation/search.html.twig
<form action="{{ path('reclamation_search') }}" >
    <input placeholder="titre.." name="titre"></input>
    <button type="submit">Search</button>
</form>

templates/reclamation/show.html.twig
{% extends 'BackOffice.html.twig' %}
{% block title %}
	Détails de la reclamation
{% endblock %}

{% block contenu %}
	<div id="layoutSidenav_content">
		<main>
			<div class="card-body">
				<table class="table">
					<tbody>
						<tr>
							<th>Id</th>
							<td>{{ reclamation.id }}</td>
						</tr>
						<tr>
							<th>Titre</th>
							<td>{{ reclamation.titreRec }}</td>
						</tr>
						<tr>
							<th>Type</th>
							<td>{{ reclamation.typeRec }}</td>
						</tr>
						<tr>
							<th>Date</th>
							<td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</td>
						</tr>

						<tr>
							<th>Conetnu</th>
							<td>{{ reclamation.contenuRec }}</td>
						</tr>
						<tr>
							<th>Status</th>
							<td>{{ reclamation.statutRec }}</td>
						</tr>
					</tbody>
				</table>


				<div
					class="row mb-3">
					{# <div class="col-md-6">
																<a class="btn btn-primary btn-block" href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">Modifier</a>
															</div> #}
					<div class="col-md-6">
						{{ include('reclamation/_delete_form.html.twig', {'class':'btn btn-primary btn-block'}) }}
					</div>
					<div class="col-md-6">
						<a href="{{ path('app_reclamation_index') }}">Retour à la liste</a>
					</div>
				</div>
			</div>
		</main>
	{% endblock %}