src/Entity/Repons.php
<?php

namespace App\Entity;

use App\Repository\ReponsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
#[ORM\Entity(repositoryClass: ReponsRepository::class)]
class Repons
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?string $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank (message: "La date est requise!")]
    private ?\DateTimeInterface $date_rep = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank (message: "La description est requise!")]
    #[Assert\Length (max:255)]
    private ?string $contenu_rep = null;

    #[ORM\Column]
    #[Assert\NotBlank (message: "Le status est requise!")]
    #[Assert\Length (max:255)]
    #[Assert\Choice(choices: ["NON_TRAITE", "TRAITE", "EN_ATTENTE"])]
    private ?string $status_rep = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Reclamation $id_reclamation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateRep(): ?\DateTimeInterface
    {
        return $this->date_rep;
    }

    public function setDateRep(\DateTimeInterface $date_rep): self
    {
        $this->date_rep = $date_rep;

        return $this;
    }

    public function getContenuRep(): ?string
    {
        return $this->contenu_rep;
    }

    public function setContenuRep(string $contenu_rep): self
    {
        $this->contenu_rep = $contenu_rep;

        return $this;
    }

    public function getStatusRep(): ?string
    {
        return $this->status_rep;
    }

    public function setStatusRep(string $status_rep): self
    {
        $this->status_rep = $status_rep;

        return $this;
    }

    public function getIdReclamation(): ?Reclamation
    {
        return $this->id_reclamation;
    }

    public function setIdReclamation(?Reclamation $id_reclamation): self
    {
        $this->id_reclamation = $id_reclamation;

        return $this;
    }
}

src/Controller/ReponsController.php
<?php

namespace App\Controller;

use App\Entity\Repons;
use App\Form\Repons1Type;
use App\Repository\ReponsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/repons')]
class ReponsController extends AbstractController
{
    #[Route('/', name: 'app_repons_index', methods: ['GET'])]
    public function index(ReponsRepository $reponsRepository): Response
    {
        return $this->render('repons/index.html.twig', [
            'repons' => $reponsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_repons_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReponsRepository $reponsRepository): Response
    {
        $repon = new Repons();
        $form = $this->createForm(Repons1Type::class, $repon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponsRepository->save($repon, true);

            return $this->redirectToRoute('app_repons_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repons/new.html.twig', [
            'repon' => $repon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_repons_show', methods: ['GET'])]
    public function show(Repons $repon): Response
    {
        return $this->render('repons/show.html.twig', [
            'repon' => $repon,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_repons_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Repons $repon, ReponsRepository $reponsRepository): Response
    {
        $form = $this->createForm(Repons1Type::class, $repon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponsRepository->save($repon, true);

            return $this->redirectToRoute('app_repons_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repons/edit.html.twig', [
            'repon' => $repon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_repons_delete', methods: ['POST'])]
    public function delete(Request $request, Repons $repon, ReponsRepository $reponsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$repon->getId(), $request->request->get('_token'))) {
            $reponsRepository->remove($repon, true);
        }

        return $this->redirectToRoute('app_repons_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/repons/_delete_form.html.twig
<form method="post" action="{{ path('app_repons_delete', {'id': repon.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ repon.id) }}">
    <button class="btn">Delete</button>
</form>

templates/repons/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/repons/edit.html.twig
{% extends 'BackOffice.html.twig' %}

{% block title %}
	Modifier la Reponse
{% endblock %}

{% block contenu %}
	<div id="layoutSidenav_content">
		<main>
			<div id="layoutAuthentication">
				<div id="layoutAuthentication_content">
					<main>
						<div class="container">
							<div class="row justify-content-center">
								<div class="col-lg-7">
									<div class="card shadow-lg border-0 rounded-lg mt-5">
										<div class="card-header">
											<h3 class="text-center font-weight-light my-4">Modifier la reponse</h3>
										</div>
										<div class="card-body">
											{{form_start(form,{'attr':{'novalidate':'novalidate'}})}}
											<div class="row mb-3">

												<div class="col-md-6">
													<div class="form-floating">
														{{form_widget(form.date_rep,{'attr':{'class':'form-control datetimepicker'}})}}
														<label for="inputLastName">Date et Heure</label>
													</div>
												</div>
											</div>

											<div class="row mb-3">
												<div class="col-md-6">
													<div class="form-floating mb-3 mb-md-0">
														{{form_widget(form.contenu_rep,{'attr':{'class':'form-control'}})}}
														<label for="inputFirstName">contenu</label>
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-floating">
														{{form_widget(form.status_rep,{'attr':{'class':'form-control'}})}}
														<label for="inputLastName">status</label>
													</div>
												</div>

											</div>

											<div class="row mb-3">
												<div class="col-md-6"></div>
											</div>
											<div class="mt-4 mb-0">
												<div class="d-grid">
													{{ include('repons/_form.html.twig', {'button_label': 'Modifier'}) }}
												</div>
											</div>
											<div class="mt-4 mb-0">
												<div class="d-grid">
													{{ include('repons/_delete_form.html.twig') }}
												</div>
											</div>


											{{form_end(form)}}
										</div>
										<div class="card-footer text-center py-3">
											<div class="small">
												<a type="button" class="btn btn-primary" href="{{ path('app_repons_index') }}">Retour à la liste</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</main>
				</div>
			</main>
		{% endblock %}

templates/repons/index.html.twig
{% extends 'BackOffice.html.twig' %}

{% block contenu %}
	<div id="layoutSidenav_content">

		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>Date Repnse</th>
					<th>Contenu Reponse</th>
					<th>Status Reponse</th>
					<th>Reclamant</th>
					<th>actions</th>
				</tr>
			</thead>
			<tbody>
				{% for repon in repons %}
					<tr>
						<td>{{ repon.id }}</td>
						<td>{{ repon.dateRep ? repon.dateRep|date('Y-m-d') : '' }}</td>
						<td>{{ repon.contenuRep }}</td>
						<td>
							{% if repon.statusRep == 1 %}
								<div class="progress">
									<div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
							</div>

						{%  elseif repon.statusRep == 2 %}
							<div class="progress">
								<div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
							</div>
						</div>

					{% elseif repon.statusRep == 3 %}
						<div class="progress">
							<div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
				{% endif %}
			</tbody>
		</td>
		<td>{{ repon.statusRep }}</td>
		<td>{{ repon.getIdReclamation()}}</td>
		<td>
			<a type="button" class="btn btn-warning" href="{{ path('app_repons_show', {'id': repon.id}) }}">show</a>
			<a type="button" class="btn btn-info" href="{{ path('app_repons_edit', {'id': repon.id}) }}">edit</a>
		</td>
	</tr>
{% else %}
	<tr>
		<td colspan="5">no records found</td>
	</tr>
{% endfor %}</tbody></table>{# <centre><a role="button" class="btn btn-primary" href="{{ path('app_repons_new') }}">Create new</a></centre> #}{% endblock %}

templates/repons/new.html.twig
{% extends 'BackOffice.html.twig' %}

{% block title %}
	Reponse
{% endblock %}

{% block contenu %}
	<div id="layoutSidenav_content">
		<main>
			<div id="layoutAuthentication">
				<div id="layoutAuthentication_content">
					<main>
						<div class="container">
							<div class="row justify-content-center">
								<div class="col-lg-7">
									<div class="card shadow-lg border-0 rounded-lg mt-5">
										<div class="card-header">
											<h3 class="text-center font-weight-light my-4">Créer une Reponse</h3>
										</div>
										<div class="card-body">
											{{form_start(form,{'attr':{'novalidate':'novalidate'}})}}
											<div class="col-md-6">
												<div class="form-floating">
													{% if form_errors(form.date_rep) %}
														{{form_errors(form.date_rep,{'attr':{'class':'form-control'}})}}
														{{form_widget(form.date_rep,{'attr':{'class':'form-control datetimepicker'}})}}

														<label for="inputLastName">Date et Heure</label>
													{% endif %}
												</div>
											</div>
										</div>

										<div class="row mb-3">
											<div class="col-md-6">
												<div class="form-floating mb-3 mb-md-0">
													{% if form_errors(form.contenu_rep) %}
														{{form_errors(form.contenu_rep,{'attr':{'class':'form-control'}})}}
														{{form_widget(form.contenu_rep,{'attr':{'class':'form-control'}})}}
														<label for="inputFirstName">Contenu</label>
													{% endif %}
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-floating">
													{% if form_errors(form.status_rep) %}
														{{form_errors(form.status_rep,{'attr':{'class':'form-control'}})}}
														{{form_widget(form.status_rep,{'attr':{'class':'form-control'}})}}
														<label for="inputLastName">Status</label>
													{% endif %}
												</div>
											</div>
										</div>
										<div class="mt-4 mb-0">
											<div class="d-grid">
												{{ include('repons/_form.html.twig', {'button_label': 'Valider'}, {'class':'btn btn-primary '}) }}
											</div>
										</div>
										<div class="card-footer text-center py-3">
											<div class="small">
												<a a type="button" class="btn btn-primary" href="{{ path('app_repons_index') }}">Retour à la liste</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</main>
				</div>
			</main>
		{% endblock %}

templates/repons/show.html.twig
{% extends 'BackOffice.html.twig' %}

{% block title %}
	Détails de la Reponse
{% endblock %}

{% block contenu %}
	<div id="layoutSidenav_content">
		<main>
			<div class="card-body">
				<table class="table">
					<tbody>
						<tr>
							<th>Id</th>
							<td>{{ repon.id }}</td>
						</tr>
						<th>Date</th>
						<td>{{ repon.dateRep ? repon.dateRep|date('Y-m-d') : '' }}</td>
					</tbody>
				</tr>

				<tr>
					<th>Conetnu</th>
					<td>{{ repon.contenuRep }}</td>
				</tr>
				<tr>
					<th>Status</th>
					<td>{{ repon.statusRep }}</td>
				</tr>
			</tbody>
		</table>


		<div class="row mb-3">
			<div class="col-md-6">
				<a class="btn btn-primary btn-block" href="{{ path('app_repons_edit', {'id': repon.id}) }}">Modifier</a>
			</div>
			<div class="col-md-6">
				{{ include('repons/_delete_form.html.twig', {'class':'btn btn-primary btn-block'}) }}
			</div>
			<div class="col-md-6">
				<a href="{{ path('app_repons_index') }}">Retour à la liste</a>
			</div>
		</div>
	</div>
</main>{% endblock %}